// Auto-generated image URL mapping
// Maps exact names from content files to Supabase URLs
// Generated: 2025-12-02T17:02:00.291Z

const SUPABASE_IMG = "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images";

export const imageUrlMap: Record<string, string> = {
  "Tony Stark / Iron Man": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tony-stark.png",
  "Doc Brown": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/doc-brown.jpg",
  "Willy Wonka": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/willy-wonka.jpg",
  "The Doctor": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/the-doctor.png",
  "Q": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/q-bond.jpg",
  "Elon Musk": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/elon-musk.jpg",
  "Steve Jobs": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/steve-jobs.jpg",
  "Nikola Tesla": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nikola-tesla.jpg",
  "Richard Branson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/richard-branson.jpg",
  "Leonardo da Vinci": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/leonardo-da-vinci.png",
  "Bruce Wayne / Batman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/batman.jpg",
  "Sherlock Holmes": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sherlock-holmes.jpg",
  "Hermione Granger": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hermione-granger.jpg",
  "Spock": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/spock.jpg",
  "Walter White": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/walter-white.png",
  "Bill Gates": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bill-gates.jpg",
  "Marie Curie": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/marie-curie.jpg",
  "Isaac Newton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/isaac-newton.jpg",
  "Ada Lovelace": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ada-lovelace.jpg",
  "Alan Turing": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/alan-turing.jpg",
  "Ted Lasso": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ted-lasso.jpg",
  "Elle Woods": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/elle-woods.jpg",
  "Star-Lord / Peter Quill": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/star-lord.png",
  "Jack Sparrow": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jack-sparrow.jpg",
  "Michael Scott": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/michael-scott.png",
  "Oprah Winfrey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/oprah-winfrey.jpg",
  "Ellen DeGeneres": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ellen-degeneres.jpg",
  "Tony Robbins": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tony-robbins.jpg",
  "Dwayne Johnson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dwayne-johnson.jpg",
  "Richard Simmons": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/richard-simmons.jpg",
  "Captain America / Steve Rogers": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/captain-america.jpg",
  "Admiral Adama": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/admiral-adama.jpg",
  "Ned Stark": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ned-stark.jpg",
  "Jean-Luc Picard": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jean-luc-picard.jpg",
  "Obi-Wan Kenobi": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/obi-wan-kenobi.png",
  "Angela Merkel": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/angela-merkel.jpg",
  "Warren Buffett": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/warren-buffett.jpg",
  "Colin Powell": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/colin-powell.jpg",
  "Tim Cook": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tim-cook.jpg",
  "Sandra Day O'Connor": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sandra-day-oconnor.jpg",
  "Samwise Gamgee": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/samwise-gamgee.jpg",
  "Olaf": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/olaf.png",
  "Hagrid": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hagrid.jpg",
  "Paddington Bear": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/paddington-bear.jpg",
  "Baymax": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/baymax.jpg",
  "Dolly Parton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dolly-parton.jpg",
  "Fred Rogers": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/fred-rogers.png",
  "Princess Diana": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/princess-diana.jpg",
  "Keanu Reeves": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/keanu-reeves.jpg",
  "Steve Irwin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/steve-irwin.jpg",
  "Atticus Finch": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/atticus-finch.jpg",
  "Mufasa": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mufasa.webp",
  "Gandalf": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/gandalf.jpg",
  "Wonder Woman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/wonder-woman.jpg",
  "King T'Chaka": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/king-tchaka.jpg",
  "Nelson Mandela": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nelson-mandela.jpg",
  "Ruth Bader Ginsburg": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ruth-bader-ginsburg.jpg",
  "Malala Yousafzai": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/malala-yousafzai.jpg",
  "John Lewis": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-lewis.jpg",
  "Desmond Tutu": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/desmond-tutu.jpg",
  "Indiana Jones": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/indiana-jones.jpg",
  "Moana": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/moana.jpg",
  "Captain Jack Sparrow": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jack-sparrow.jpg",
  "Lara Croft": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lara-croft.png",
  "Dora the Explorer": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dora-the-explorer.svg",
  "Anthony Bourdain": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/anthony-bourdain.jpg",
  "Jane Goodall": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jane-goodall.jpg",
  "Bear Grylls": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bear-grylls.jpg",
  "Jacques Cousteau": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jacques-cousteau.jpg",
  "Neil Armstrong": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/neil-armstrong.jpg",
  "Alfred Pennyworth": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/alfred-pennyworth.jpg",
  "Iroh": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/iroh.jpg",
  "Groot": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/groot.jpeg",
  "Marge Simpson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/marge-simpson.svg",
  "Dalai Lama": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dalai-lama.jpg",
  "Tom Hanks": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tom-hanks.jpg",
  "Morgan Freeman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/morgan-freeman.jpg",
  "Bob Ross": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bob-ross.jpg",
  "Thich Nhat Hanh": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/thich-nhat-hanh.jpg",
  "Professor X / Charles Xavier": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/professor-x.jpg",
  "Dumbledore": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dumbledore.jpg",
  "T'Challa / Black Panther": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tchalla.jpg",
  "Morpheus": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/morpheus.jpg",
  "Vision": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/vision-mcu.jpg",
  "Satya Nadella": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/satya-nadella.jpg",
  "Jeff Bezos": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jeff-bezos.jpg",
  "Sundar Pichai": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sundar-pichai.jpg",
  "Mary Barra": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mary-barra.jpg",
  "Reed Hastings": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/reed-hastings.jpg",
  "Aang": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/aang.png",
  "Belle": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/belle.jpg",
  "Newt Scamander": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/newt-scamander.jpg",
  "Steven Universe": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/steven-universe.png",
  "Amélie Poulain": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/amelie.jpg",
  "Brené Brown": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/brene-brown.jpg",
  "Mr. Rogers": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/fred-rogers.png",
  "Hayao Miyazaki": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hayao-miyazaki.jpg",
  "Jane Austen": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jane-austen.jpg",
  "Emily Dickinson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/emily-dickinson.png",
  "Leslie Knope": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/leslie-knope.png",
  "Miranda Priestly": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/miranda-priestly.jpg",
  "Harvey Specter": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/harvey-specter.jpg",
  "Don Draper": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/don-draper.jpg",
  "Rocky Balboa": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/rocky-balboa.jpeg",
  "Serena Williams": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/serena-williams.jpg",
  "Kobe Bryant": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kobe-bryant.jpg",
  "Beyoncé": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/beyonce.jpg",
  "Michael Jordan": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/michael-jordan.jpg",
  "Indra Nooyi": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/indra-nooyi.jpg",
  "Data": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/data-tng.jpg",
  "Lisbeth Salander": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lisbeth-salander.jpg",
  "Spencer Reid": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/spencer-reid.jpg",
  "Amy Santiago": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/amy-santiago.png",
  "Albert Einstein": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/albert-einstein.jpg",
  "Stephen Hawking": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/stephen-hawking.jpg",
  "Katherine Johnson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/katherine-johnson.jpg",
  "Nate Silver": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nate-silver.jpg",
  "Carl Sagan": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/carl-sagan.jpg",
  "Michelle Obama": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/michelle-obama.jpg",
  "Arnold Schwarzenegger": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/arnold-schwarzenegger.jpg",
  "Jodie Foster": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jodie-foster.jpg",
  "Christopher Nolan": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/christopher-nolan.jpg",
  "Ayn Rand": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ayn-rand.jpg",
  "Friedrich Nietzsche": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/friedrich-nietzsche.jpg",
  "Hillary Clinton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hillary-clinton.jpg",
  "Vladimir Putin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/vladimir-putin.jpg",
  "Mark Zuckerberg": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mark-zuckerberg.jpg",
  "Cillian Murphy": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/cillian-murphy.jpg",
  "Jay-Z": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jay-z.jpg",
  "Stanley Kubrick": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/stanley-kubrick.jpg",
  "Samantha Power": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/samantha-power.jpg",
  "Ludwig van Beethoven": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ludwig-van-beethoven.jpg",
  "Martina Navratilova": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/martina-navratilova.jpg",
  "Charles Darwin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/charles-darwin.jpg",
  "Abraham Lincoln": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/abraham-lincoln.jpg",
  "Socrates": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/socrates.jpg",
  "Tina Fey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tina-fey.jpg",
  "Larry Page": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/larry-page.jpg",
  "Rene Descartes": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/rene-descartes.jpg",
  "Blaise Pascal": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/blaise-pascal.jpg",
  "Kristen Stewart": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kristen-stewart.jpg",
  "Jesse Eisenberg": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jesse-eisenberg.jpg",
  "Randall Munroe": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/randall-munroe.jpg",
  "Harper Lee": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/harper-lee.jpg",
  "Isaac Asimov": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/isaac-asimov.jpg",
  "Carl Jung": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/carl-jung.jpg",
  "Edward Snowden": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/edward-snowden.jpg",
  "Richard Dawkins": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/richard-dawkins.jpg",
  "Ellen Page": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ellen-page.jpg",
  "Immanuel Kant": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/immanuel-kant.jpg",
  "Margaret Thatcher": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/margaret-thatcher.jpg",
  "Franklin D. Roosevelt": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/franklin-d-roosevelt.jpg",
  "Sheryl Sandberg": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sheryl-sandberg.jpg",
  "Napoleon Bonaparte": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/napoleon-bonaparte.jpg",
  "Gordon Ramsay": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/gordon-ramsay.jpg",
  "Adele": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/adele.jpg",
  "Condoleezza Rice": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/condoleezza-rice.jpg",
  "Julius Caesar": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/julius-caesar.jpg",
  "Harrison Ford": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/harrison-ford.jpg",
  "Patrick Stewart": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/patrick-stewart.jpg",
  "Whoopi Goldberg": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/whoopi-goldberg.jpg",
  "David Letterman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/david-letterman.jpg",
  "Jim Carrey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jim-carrey.jpg",
  "Charlize Theron": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/charlize-theron.jpg",
  "George Clooney": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/george-clooney.jpg",
  "Quentin Tarantino": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/quentin-tarantino.jpg",
  "Mark Twain": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mark-twain.jpg",
  "Thomas Edison": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/thomas-edison.jpg",
  "Sacha Baron Cohen": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sacha-baron-cohen.jpg",
  "Benjamin Franklin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/benjamin-franklin.jpg",
  "Celine Dion": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/celine-dion.jpg",
  "Weird Al Yankovic": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/weird-al-yankovic.jpg",
  "Adam Savage": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/adam-savage.jpg",
  "Ryan Reynolds": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ryan-reynolds.jpg",
  "Neil Patrick Harris": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/neil-patrick-harris.jpg",
  "Amy Poehler": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/amy-poehler.jpg",
  "Voltaire": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/voltaire.jpg",
  "Conan O'Brien": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/conan-obrien.jpg",
  "Matthew Perry": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/matthew-perry.jpg",
  "Robert Downey Jr.": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/robert-downey-jr.jpg",
  "Oscar Wilde": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/oscar-wilde.jpg",
  "Jon Stewart": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jon-stewart.jpg",
  "Hugh Laurie": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hugh-laurie.jpg",
  "Federico Fellini": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/federico-fellini.jpg",
  "Martin Luther King Jr.": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/martin-luther-king-jr.jpg",
  "Lady Gaga": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lady-gaga.jpg",
  "Mahatma Gandhi": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mahatma-gandhi.jpg",
  "Mother Teresa": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mother-teresa.jpg",
  "Taylor Swift": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/taylor-swift.png",
  "Cate Blanchett": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/cate-blanchett.jpg",
  "Fyodor Dostoevsky": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/fyodor-dostoevsky.jpg",
  "Plato": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/plato.png",
  "Agatha Christie": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/agatha-christie.png",
  "Noam Chomsky": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/noam-chomsky.jpg",
  "Marilyn Manson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/marilyn-manson.jpg",
  "Nicole Kidman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nicole-kidman.jpg",
  "Al Pacino": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/al-pacino.jpg",
  "Edward Norton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/edward-norton.jpg",
  "Daniel Day-Lewis": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/daniel-day-lewis.jpg",
  "Rooney Mara": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/rooney-mara.jpg",
  "Adolf Hitler": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/adolf-hitler.jpg",
  "Simone de Beauvoir": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/simone-de-beauvoir.jpg",
  "William Shakespeare": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/william-shakespeare.jpg",
  "J.R.R. Tolkien": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/j-r-r-tolkien.jpg",
  "John Lennon": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-lennon.jpg",
  "Edgar Allan Poe": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/edgar-allan-poe.jpg",
  "Kurt Cobain": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kurt-cobain.jpg",
  "Audrey Hepburn": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/audrey-hepburn.jpg",
  "Vincent van Gogh": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/vincent-van-gogh.jpg",
  "Johnny Depp": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/johnny-depp.jpg",
  "Tim Burton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tim-burton.jpg",
  "Florence Welch": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/florence-welch.jpg",
  "Bjork": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bjork.png",
  "Andrew Garfield": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/andrew-garfield.jpg",
  "Heath Ledger": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/heath-ledger.jpg",
  "Emily Blunt": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/emily-blunt.jpg",
  "Louis C.K.": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/louis-c-k.png",
  "Tom Hiddleston": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tom-hiddleston.jpg",
  "Helena Bonham Carter": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/helena-bonham-carter.jpg",
  "Virginia Woolf": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/virginia-woolf.jpg",
  "Barack Obama": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/barack-obama.jpg",
  "Maya Angelou": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/maya-angelou.jpg",
  "Reese Witherspoon": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/reese-witherspoon.jpg",
  "Bono": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bono.jpg",
  "Jennifer Lawrence": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jennifer-lawrence.jpg",
  "John Cusack": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-cusack.jpg",
  "Matthew McConaughey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/matthew-mcconaughey.jpg",
  "John Legend": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-legend.jpg",
  "Emma Thompson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/emma-thompson.jpg",
  "Pope Francis": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/pope-francis.jpg",
  "Ralph Nader": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ralph-nader.jpg",
  "Ben Stiller": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ben-stiller.jpg",
  "Dakota Fanning": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dakota-fanning.jpg",
  "Sean Connery": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sean-connery.jpg",
  "Kate Winslet": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kate-winslet.png",
  "Drake": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/drake.jpg",
  "Robin Williams": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/robin-williams.jpg",
  "Walt Disney": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/walt-disney.jpg",
  "Will Smith": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/will-smith.jpg",
  "Sandra Bullock": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sandra-bullock.jpg",
  "Russell Brand": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/russell-brand.jpg",
  "Anne Frank": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/anne-frank.jpg",
  "Drew Barrymore": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/drew-barrymore.jpg",
  "Janis Joplin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/janis-joplin.jpg",
  "Jerry Seinfeld": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jerry-seinfeld.jpg",
  "Keira Knightley": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/keira-knightley.png",
  "Hunter S. Thompson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hunter-s-thompson.jpg",
  "Gwen Stefani": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/gwen-stefani.jpg",
  "Kelly Clarkson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kelly-clarkson.jpg",
  "Alicia Keys": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/alicia-keys.jpg",
  "Cher": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/cher.jpg",
  "George Washington": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/george-washington.jpg",
  "Queen Elizabeth II": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/queen-elizabeth-ii.jpg",
  "Denzel Washington": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/denzel-washington.jpg",
  "Anthony Hopkins": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/anthony-hopkins.jpg",
  "Jeff Sessions": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jeff-sessions.jpg",
  "Natalie Portman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/natalie-portman.jpg",
  "Robert De Niro": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/robert-de-niro.jpg",
  "Sting": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sting.jpg",
  "Julia Roberts": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/julia-roberts.jpg",
  "Matt Damon": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/matt-damon.jpg",
  "Jackie Chan": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jackie-chan.jpg",
  "Karl Marx": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/karl-marx.png",
  "Henry Ford": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/henry-ford.png",
  "Sigmund Freud": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sigmund-freud.jpg",
  "George H.W. Bush": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/george-h-w-bush.jpg",
  "Kate Middleton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kate-middleton.jpg",
  "Rosa Parks": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/rosa-parks.jpg",
  "Anne Hathaway": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/anne-hathaway.jpg",
  "Vin Diesel": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/vin-diesel.jpg",
  "Kim Kardashian": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kim-kardashian.jpg",
  "Halle Berry": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/halle-berry.jpg",
  "Selena Gomez": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/selena-gomez.jpg",
  "Jimmy Carter": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jimmy-carter.jpg",
  "Dr. Dre": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dr-dre.jpg",
  "Tiger Woods": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tiger-woods.jpg",
  "Bruce Willis": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bruce-willis.jpg",
  "50 Cent": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/50-cent.jpg",
  "Christopher Walken": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/christopher-walken.jpg",
  "Katie Holmes": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/katie-holmes.jpg",
  "Lance Armstrong": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lance-armstrong.jpg",
  "Aretha Franklin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/aretha-franklin.jpg",
  "David Copperfield": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/david-copperfield.jpg",
  "Ed Sheeran": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ed-sheeran.jpg",
  "John D. Rockefeller": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-d-rockefeller.jpg",
  "Judge Judy": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/judge-judy.jpg",
  "Lyndon B. Johnson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lyndon-b-johnson.jpg",
  "Martha Stewart": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/martha-stewart.jpg",
  "Sonia Sotomayor": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sonia-sotomayor.jpg",
  "Dr. Phil": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/dr-phil.jpg",
  "Michelle Pfeiffer": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/michelle-pfeiffer.jpg",
  "Vince Lombardi": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/vince-lombardi.jpg",
  "Emma Watson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/emma-watson.jpg",
  "Alec Baldwin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/alec-baldwin.jpg",
  "Nancy Pelosi": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nancy-pelosi.jpg",
  "John Wayne": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-wayne.jpg",
  "Sam Walton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sam-walton.jpg",
  "Frank Sinatra": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/frank-sinatra.jpg",
  "Billy Graham": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/billy-graham.jpg",
  "Mike Pence": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mike-pence.jpg",
  "Bernard Law Montgomery": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bernard-law-montgomery.jpg",
  "Douglas MacArthur": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/douglas-macarthur.jpg",
  "Kamala Harris": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kamala-harris.jpg",
  "Bill Clinton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bill-clinton.jpg",
  "Jennifer Garner": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jennifer-garner.jpg",
  "Steve Harvey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/steve-harvey.jpg",
  "Hugh Jackman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/hugh-jackman.jpg",
  "Danny DeVito": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/danny-devito.jpg",
  "Mariah Carey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mariah-carey.png",
  "Jennifer Lopez": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jennifer-lopez.jpg",
  "Whitney Houston": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/whitney-houston.jpeg",
  "Tyra Banks": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tyra-banks.jpg",
  "Larry King": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/larry-king.jpg",
  "Andrew Carnegie": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/andrew-carnegie.jpg",
  "Sally Field": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sally-field.jpg",
  "Nancy Reagan": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nancy-reagan.jpg",
  "Mary Tyler Moore": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mary-tyler-moore.jpg",
  "Pope John Paul II": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/pope-john-paul-ii.jpg",
  "Elton John": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/elton-john.jpg",
  "Prince William": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/prince-william.jpg",
  "Céline Dion": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/celine-dion.jpg",
  "Clint Eastwood": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/clint-eastwood.jpg",
  "Amelia Earhart": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/amelia-earhart.jpg",
  "Bruce Lee": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bruce-lee.jpg",
  "Tom Cruise": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tom-cruise.jpg",
  "Scarlett Johansson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/scarlett-johansson.jpg",
  "Daniel Craig": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/daniel-craig.jpg",
  "Steve McQueen": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/steve-mcqueen.jpg",
  "Megan Fox": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/megan-fox.jpg",
  "Keith Richards": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/keith-richards.jpg",
  "Chuck Yeager": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/chuck-yeager.jpg",
  "Milla Jovovich": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/milla-jovovich.jpg",
  "Eminem": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/eminem.jpg",
  "Simon Cowell": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/simon-cowell.jpg",
  "James Bond": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/james-bond.jpg",
  "Katharine Hepburn": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/katharine-hepburn.jpg",
  "Bob Dylan": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bob-dylan.jpg",
  "Frida Kahlo": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/frida-kahlo.jpg",
  "Prince": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/prince.png",
  "Lana Del Rey": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lana-del-rey.jpg",
  "Michael Jackson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/michael-jackson.jpg",
  "Marilyn Monroe": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/marilyn-monroe.jpg",
  "Rihanna": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/rihanna.png",
  "Brad Pitt": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/brad-pitt.jpg",
  "Jimi Hendrix": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jimi-hendrix.jpg",
  "David Bowie": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/david-bowie.jpg",
  "Avril Lavigne": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/avril-lavigne.jpg",
  "Pablo Picasso": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/pablo-picasso.jpg",
  "Kevin Costner": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kevin-costner.jpg",
  "Britney Spears": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/britney-spears.jpg",
  "Ryan Gosling": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ryan-gosling.jpg",
  "John Travolta": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-travolta.jpg",
  "Billie Eilish": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/billie-eilish.jpg",
  "Jared Leto": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jared-leto.jpg",
  "Amy Winehouse": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/amy-winehouse.jpg",
  "Ernest Hemingway": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ernest-hemingway.jpg",
  "Madonna": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/madonna.jpg",
  "Donald Trump": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/donald-trump.jpg",
  "Eddie Murphy": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/eddie-murphy.jpg",
  "Jack Nicholson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jack-nicholson.jpg",
  "Mick Jagger": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mick-jagger.jpg",
  "Samuel L. Jackson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/samuel-l-jackson.jpg",
  "Angelina Jolie": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/angelina-jolie.jpg",
  "Nicolas Cage": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nicolas-cage.jpg",
  "Kevin Bacon": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kevin-bacon.jpg",
  "Eva Longoria": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/eva-longoria.jpg",
  "Winston Churchill": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/winston-churchill.jpg",
  "Theodore Roosevelt": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/theodore-roosevelt.jpg",
  "Lucille Ball": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lucille-ball.jpg",
  "Antonio Banderas": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/antonio-banderas.jpg",
  "Burt Reynolds": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/burt-reynolds.jpg",
  "Helen Mirren": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/helen-mirren.jpg",
  "Sylvester Stallone": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sylvester-stallone.jpg",
  "Elvis Presley": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/elvis-presley.jpg",
  "Jamie Oliver": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jamie-oliver.jpg",
  "Miley Cyrus": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/miley-cyrus.jpg",
  "Will Ferrell": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/will-ferrell.jpg",
  "Cameron Diaz": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/cameron-diaz.jpg",
  "Justin Bieber": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/justin-bieber.jpg",
  "Adam Levine": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/adam-levine.jpg",
  "Leonardo DiCaprio": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/leonardo-dicaprio.jpg",
  "Katy Perry": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/katy-perry.jpg",
  "Pink": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/pink.jpg",
  "Steven Spielberg": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/steven-spielberg.jpg",
  "Nicki Minaj": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/nicki-minaj.jpg",
  "Magic Johnson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/magic-johnson.jpg",
  "Shakira": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/shakira.jpg",
  "Chris Rock": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/chris-rock.jpg",
  "Bob Hope": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bob-hope.jpg",
  "Zac Efron": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/zac-efron.jpg",
  "Al Gore": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/al-gore.jpg",
  "Confucius": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/confucius.jpg",
  "Gregory Peck": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/gregory-peck.jpg",
  "Meryl Streep": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/meryl-streep.jpg",
  "Jane Fonda": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jane-fonda.jpg",
  "Prince Charles": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/king-charles.jpg",
  "Captain Picard": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jean-luc-picard.jpg",
  "Lewis Carroll": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lewis-carroll.jpg",
  "Barbara Bush": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/barbara-bush.jpg",
  "Bishop Fulton Sheen": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bishop-fulton-sheen.jpg",
  "Jessica Alba": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jessica-alba.jpg",
  "Ann Landers": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ann-landers.jpg",
  "Florence Nightingale": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/florence-nightingale.jpg",
  "Eleanor Roosevelt": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/eleanor-roosevelt.jpg",
  "Stevie Wonder": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/stevie-wonder.jpg",
  "John Denver": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-denver.jpg",
  "Barry Manilow": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/barry-manilow.jpg",
  "Muhammad Ali": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/muhammed-ali.jpg",
  "Ryan Seacrest": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ryan-seacrest.jpg",
  "Kris Jenner": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kris-jenner.jpg",
  "Mitt Romney": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mitt-romney.jpg",
  "Werner Erhard": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/werner-erhard.jpg",
  "Kate Bush": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/kate-bush.jpg",
  "Joni Mitchell": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/joni-mitchell.jpg",
  "Sylvia Plath": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sylvia-plath.jpg",
  "James Dean": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/james-dean.jpg",
  "Tchaikovsky": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tchaikovsky.jpg",
  "Marlon Brando": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/marlon-brando.png",
  "Winona Ryder": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/winona-ryder.jpg",
  "Sigourney Weaver": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sigourney-weaver.jpg",
  "Oliver Sacks": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/oliver-sacks.jpg",
  "Bobby Fischer": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bobby-fischer.jpg",
  "David Byrne": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/david-byrne.jpg",
  "Ursula K. Le Guin": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ursula-k-le-guin.jpg",
  "Tilda Swinton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tilda-swinton.jpg",
  "Anthony Fauci": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/anthony-fauci.jpg",
  "Jennifer Aniston": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jennifer-aniston.jpg",
  "Woody Allen": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/woody-allen.jpg",
  "Ben Affleck": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ben-affleck.jpg",
  "Spike Lee": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/spike-lee.jpg",
  "J. Edgar Hoover": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/j-edgar-hoover.jpg",
  "Mel Gibson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mel-gibson.jpg",
  "Richard Nixon": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/richard-nixon.jpg",
  "Malcolm X": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/malcolm-x.jpg",
  "Robert F. Kennedy": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/robert-f-kennedy.jpg",
  "Diane Keaton": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/diane-keaton.jpg",
  "Rush Limbaugh": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/rush-limbaugh.jpg",
  "Jack Black": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jack-black.jpg",
  "Mozart": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/mozart.jpg",
  "Bette Midler": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/bette-midler.jpg",
  "John F. Kennedy": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-f-kennedy.jpg",
  "Sarah Silverman": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/sarah-silverman.jpg",
  "Howard Stern": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/howard-stern.jpg",
  "Timothy Leary": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/timothy-leary.jpg",
  "Barbara Walters": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/barbara-walters.jpg",
  "Queen Latifah": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/queen-latifah.jpg",
  "Russell Crowe": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/russell-crowe.jpg",
  "Fidel Castro": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/fidel-castro.jpg",
  "Roseanne Barr": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/roseanne-barr.jpg",
  "Tommy Lee Jones": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/tommy-lee-jones.jpg",
  "John McCain": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/john-mccain.jpg",
  "Indira Gandhi": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/indira-gandhi.jpg",
  "Carl Rogers": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/carl-rogers.jpg",
  "Ron Howard": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ron-howard.jpg",
  "Lisa Kudrow": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/lisa-kudrow.jpg",
  "Ringo Starr": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/ringo-starr.jpg",
  "Grace Kelly": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/grace-kelly.jpg",
  "Jeff Bridges": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jeff-bridges.jpg",
  "Gloria Steinem": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/gloria-steinem.jpg",
  "Jim Henson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/jim-henson.jpg",
  "Woody Harrelson": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/woody-harrelson.jpg",
  "Renee Zellweger": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/renee-zellweger.jpg",
  "Joseph Campbell": "https://eqkcmlxxuubibzoqliee.supabase.co/storage/v1/object/public/famous-images/joseph-campbell.png"
};

// Fallback function that tries to construct URL from name
function nameToImageId(name: string): string {
  return name.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/['']/g, '')
    .replace(/\s*\/\s*/g, '-')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

export function getImageUrl(name: string): string | undefined {
  // First check exact mapping
  if (imageUrlMap[name]) {
    return imageUrlMap[name];
  }
  
  // Fallback: try to construct URL
  const id = nameToImageId(name);
  return `${SUPABASE_IMG}/${id}.jpg`;
}
