/**
 * Content Expansion Script for Main Type Pages
 * Expands 37 personality type pages to ~7,500 words each
 * Uses OpenRouter with Gemini 3 Pro Preview
 * 
 * Usage: npx tsx scripts/expand-type-content.ts
 */

import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

// Import the actual content
import { archetypes } from "../lib/archetypes";
import { mbtiTypes } from "../lib/mbti-content";
import { enneagramTypes } from "../lib/enneagram-content";

dotenv.config({ path: ".env.local" });

const OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1";
const MODEL = "google/gemini-3-pro-preview";

// Parallel execution settings
const PARALLEL_BATCH_SIZE = 10; // Run 10 at a time
const DELAY_BETWEEN_BATCHES = 3000; // 3 seconds between batches
const TARGET_WORD_COUNT = 7500;
const MAX_RETRIES = 2; // Retry up to 2 times to hit word count

interface OpenRouterMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

function getApiKey(): string {
  const key = process.env.OPENROUTER_API_KEY;
  if (!key) {
    throw new Error("OPENROUTER_API_KEY is not set in environment variables");
  }
  return key;
}

async function generateContent(messages: OpenRouterMessage[]): Promise<string> {
  const apiKey = getApiKey();

  const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
      "HTTP-Referer": "https://prism7.app",
      "X-Title": "PRISM-7 Content Expander",
    },
    body: JSON.stringify({
      model: MODEL,
      messages,
      temperature: 0.7,
      max_tokens: 24000, // Allow for longer responses to hit 7500+ words
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`OpenRouter API error: ${response.status} - ${error}`);
  }

  const data = await response.json();
  return data.choices[0]?.message?.content || "";
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ============================================================================
// PRISM-7 METHODOLOGY CONTEXT
// ============================================================================

const PRISM_METHODOLOGY_CONTEXT = `
PRISM-7 is a next-generation personality assessment built on the HEXACO+ model, which improves upon traditional frameworks like MBTI and Big Five in several key ways:

1. **HEXACO Foundation**: Unlike MBTI's binary categories or Big Five's limited scope, HEXACO adds the crucial Honesty-Humility dimension, which predicts ethical behavior, manipulation tendencies, and authentic vs. performative social engagement.

2. **Seven Dimensions**: PRISM-7 measures:
   - Openness (creativity, intellectual curiosity, aesthetic sensitivity)
   - Conscientiousness (organization, self-discipline, goal-pursuit)
   - Extraversion (social energy, assertiveness, positive emotionality)
   - Agreeableness (cooperation, trust, empathy)
   - Emotional Resilience (stress tolerance, emotional stability - importantly framed positively, not as "neuroticism")
   - Honesty-Humility (authenticity, fairness, lack of entitlement)
   - Adaptability (flexibility, comfort with change, cognitive agility)

3. **Why This Matters**: 
   - MBTI uses binary categories (you're either Introverted OR Extraverted), ignoring that most people fall in the middle
   - MBTI's "Intuition vs. Sensing" conflates multiple distinct traits
   - Big Five's "Neuroticism" is deficit-focused; PRISM-7's "Emotional Resilience" is strength-focused
   - Neither MBTI nor Big Five capture Honesty-Humility, which is crucial for predicting workplace ethics, relationship authenticity, and leadership integrity
   - Neither adequately measures Adaptability, increasingly vital in modern environments

4. **Research Backing**: HEXACO has stronger predictive validity than Big Five for antisocial behavior, job performance in trust-sensitive roles, and relationship satisfaction. PRISM-7 adds Adaptability based on contemporary research on psychological flexibility.

When writing about personality types, integrate these insights to show how PRISM-7 provides a more complete, nuanced picture than legacy frameworks.
`;

// ============================================================================
// EXPANSION PROMPTS
// ============================================================================

const SYSTEM_PROMPT = `You are an expert personality psychology writer creating deeply detailed, original content for a next-generation personality assessment platform (PRISM-7).

${PRISM_METHODOLOGY_CONTEXT}

CRITICAL WRITING REQUIREMENTS:

1. **ABSOLUTE ORIGINALITY**: Your content must feel hand-crafted by a seasoned psychologist, not generated by AI. Avoid:
   - Clichéd openings like "In today's fast-paced world..." or "When it comes to..."
   - Filler phrases like "It's important to note that..." or "One might say..."
   - Generic platitudes that could apply to any type
   - Predictable paragraph structures

2. **DEEP PSYCHOLOGICAL INSIGHT**: Go beyond surface behaviors to underlying mechanisms:
   - What cognitive patterns drive this type's behavior?
   - What are the second and third-order effects of their core traits?
   - How do their strengths become weaknesses in specific contexts?
   - What developmental trajectory is typical for this type?

3. **VIVID SPECIFICITY**: Replace abstract descriptions with concrete scenarios:
   - Instead of "They are good at planning" → "They're the person who creates a shared Google Doc for a weekend trip, complete with backup restaurant options and rain contingencies"
   - Include sensory details, dialogue snippets, and recognizable micro-moments

4. **PRISM-7 INTEGRATION**: Show how this type maps to PRISM-7 dimensions and what traditional frameworks miss about them. Highlight the nuances that HEXACO+ captures that MBTI/Enneagram cannot.

5. **INTELLECTUAL HONESTY**: Acknowledge complexity, paradoxes, and individual variation. Avoid making types sound like monolithic categories.

6. **TARGET: 7,500+ WORDS**: This is a comprehensive resource. Each section should be rich with detail, examples, and insight. Do not pad with repetition—add genuine new content.

OUTPUT FORMAT: Return valid JSON matching the exact structure provided, with dramatically expanded content in each field.`;

function buildMBTIExpansionPrompt(typeCode: string, existingContent: any): string {
  return `Expand this MBTI type content to approximately 7,500 words total while maintaining the exact JSON structure.

CURRENT CONTENT FOR ${typeCode}:
${JSON.stringify(existingContent, null, 2)}

EXPANSION REQUIREMENTS:

1. **description[]**: Expand from ${existingContent.description?.length || 0} paragraphs to 10-14 substantial paragraphs. Cover:
   - The lived experience of being this type (what does their internal world feel like?)
   - How they developed these patterns (childhood, formative experiences)
   - The paradoxes and tensions within this type
   - How they're commonly misunderstood
   - Their relationship with their inferior function
   - How they change across life stages
   - What they're like when healthy vs. stressed
   - Their unique gifts that other types cannot replicate
   
2. **cognitiveFunctions**: Expand each function description to 150-200 words with:
   - How this function manifests in daily decisions
   - Specific examples of this function in action
   - How it interacts with other functions in the stack
   - Common misunderstandings about this function in this position

3. **strengths[]**: Expand each strength object to include 80-120 word descriptions with:
   - Specific workplace/relationship scenarios demonstrating this strength
   - The underlying cognitive mechanism
   - How this strength can be developed further
   - When this strength might be mistaken for something else

4. **blindspots[]**: Expand each to 80-120 words with:
   - Real consequences of this blindspot (not just abstract descriptions)
   - How it shows up in relationships vs. work vs. personal life
   - Compassionate framing—why this blindspot exists
   - Practical mitigation strategies

5. **inRelationships**: Expand each section (romantic, friendship, workplace) to 200-300 words with:
   - Specific interaction patterns and dialogue examples
   - What partners/friends/colleagues often misunderstand
   - How they show love/loyalty in ways others might miss
   - Compatibility nuances beyond simple type pairings

6. **careerPaths[]**: Expand each career to include 100-150 word reasons with:
   - Day-in-the-life scenarios
   - Specific tasks that energize vs. drain this type
   - Career progression typical for this type
   - Warning signs of poor fit

7. **growthAdvice[]**: Expand each piece of advice to 80-120 words with:
   - Why this specific advice matters for this type
   - Concrete first steps to implement
   - What internal resistance they'll face
   - Signs of progress

8. **prismCorrelation**: Expand keyDimensions to 150-200 words explaining:
   - Exactly how this type maps to PRISM-7 dimensions
   - What PRISM-7 reveals that MBTI misses about this type
   - Why HEXACO+ provides a more nuanced understanding

Return ONLY valid JSON matching the original structure with no markdown formatting or code blocks.`;
}

function buildEnneagramExpansionPrompt(typeNum: string, existingContent: any): string {
  return `Expand this Enneagram type content to approximately 7,500 words total while maintaining the exact JSON structure.

CURRENT CONTENT FOR TYPE ${typeNum}:
${JSON.stringify(existingContent, null, 2)}

EXPANSION REQUIREMENTS:

1. **description[]**: Expand from ${existingContent.description?.length || 0} paragraphs to 10-14 substantial paragraphs. Cover:
   - The core wound that created this fixation
   - The internal logic of their coping strategy
   - How the core fear manifests in subtle, everyday moments
   - The paradox between what they seek and how they pursue it
   - Their relationship with their body/heart/head center
   - How childhood experiences shaped this pattern
   - The spiritual or existential dimension of their journey
   - What liberation looks like for this type

2. **healthLevels**: Expand each level (healthy, average, unhealthy) to 200-250 words with:
   - Observable behaviors at this level
   - Internal experience at this level
   - How others experience them at this level
   - Triggers that move them between levels
   - What this level looks like in relationships vs. work

3. **wings**: Expand each wing description to 150-200 words with:
   - How the wing modifies the core type's expression
   - Specific behavioral differences between the two wings
   - Career implications of each wing
   - Relationship patterns unique to each wing

4. **growthLine & stressLine**: Expand each to 150-200 words with:
   - How movement to this point manifests behaviorally
   - What triggers movement in this direction
   - How to recognize you're moving toward growth vs. stress
   - Integration of healthy aspects from connected types

5. **strengths[]**: Expand each to 60-80 words with specific examples
6. **challenges[]**: Expand each to 60-80 words with compassionate framing

7. **inRelationships**: Expand to 300-400 words covering:
   - Core relationship patterns rooted in the type's fixation
   - How the core fear shows up in intimacy
   - What they need from partners that they struggle to ask for
   - Their unique gifts as partners
   - Common relationship pitfalls and how to avoid them

8. **careerPaths[]**: Expand each career to include 100-120 word reasons with day-in-the-life scenarios

9. **growthAdvice[]**: Expand each to 80-100 words with:
   - The psychological mechanism behind the advice
   - Practical first steps
   - Signs of progress

10. **prismCorrelation**: Expand keyDimensions to 150-200 words explaining how PRISM-7 dimensions capture what Enneagram describes motivationally, and what HEXACO+ adds to understanding this type.

Return ONLY valid JSON matching the original structure with no markdown formatting or code blocks.`;
}

function buildPRISMExpansionPrompt(typeId: string, existingContent: any): string {
  return `Expand this PRISM-7 archetype content to approximately 7,500 words total while maintaining the exact JSON structure.

CURRENT CONTENT FOR ${typeId.toUpperCase()}:
${JSON.stringify(existingContent, null, 2)}

EXPANSION REQUIREMENTS:

1. **description[]**: Expand from ${existingContent.description?.length || 0} paragraphs to 10-14 substantial paragraphs. Cover:
   - What makes this archetype distinct from superficially similar types
   - The lived experience—what does it feel like to be this archetype?
   - How this pattern of PRISM-7 dimensions creates emergent properties
   - The developmental origins of this archetype
   - Common misconceptions about this archetype
   - How they experience flow states and what blocks them
   - Their unique contribution that no other archetype can provide
   - The growth edge—where their evolution lies

2. **strengths[]**: Expand each strength to 60-80 words with:
   - Specific manifestations in different contexts
   - The PRISM-7 dimensions underlying this strength
   - How to leverage this strength more intentionally

3. **growthAreas[]**: Expand each to 60-80 words with:
   - Why this is challenging given their PRISM-7 profile
   - Compassionate framing of the underlying need
   - Practical development strategies

4. **careerMatches[]**: Expand each career explanation to 100-150 words with:
   - Day-in-the-life scenarios
   - Why the PRISM-7 dimension pattern makes this a fit
   - What aspects of this career they'd need to watch out for
   - Career progression trajectory

5. **workStyle**: Expand to 200-300 words covering:
   - Ideal physical environment details
   - Meeting and collaboration preferences
   - Communication style at work
   - How they handle deadlines and pressure
   - What drains them vs. energizes them at work

6. **relationshipStyle**: Expand to 200-300 words covering:
   - How their PRISM-7 dimensions show up in intimacy
   - What they offer partners that's unique
   - What they need that they may not articulate
   - Common misunderstandings partners have
   - Long-term relationship evolution patterns

7. **communicationStyle**: Expand to 150-200 words with specific examples of:
   - Their verbal patterns and preferences
   - Non-verbal communication tendencies
   - How they handle conflict communication
   - Written vs. verbal preferences

8. **atYourBest**: Expand to 150-200 words with:
   - Specific scenarios of peak performance
   - What conditions enable this state
   - How others experience them at their best

9. **whenStressed**: Expand to 150-200 words with:
   - Observable stress behaviors
   - Internal experience of stress
   - What triggers stress for this archetype
   - De-escalation strategies

Return ONLY valid JSON matching the original structure with no markdown formatting or code blocks.`;
}

// ============================================================================
// EXPANSION WITH RETRY FOR WORD COUNT
// ============================================================================

function countWords(obj: any): number {
  const text = JSON.stringify(obj);
  return text.split(/\s+/).length;
}

function buildExtensionPrompt(currentContent: any, currentWordCount: number, targetWordCount: number, framework: string): string {
  const wordsNeeded = targetWordCount - currentWordCount + 500; // Add buffer
  
  return `I have personality type content that is ${currentWordCount} words. I need you to ADD approximately ${wordsNeeded} more words of NEW content to reach ${targetWordCount}+ total.

CURRENT CONTENT TO EXTEND:
${JSON.stringify(currentContent, null, 2)}

EXTENSION TASK - Add NEW paragraphs/content to these specific areas:

1. **description[]**: Add 3-5 NEW paragraphs covering:
   - A "day in the life" narrative showing how this type navigates morning routines, work challenges, and evening wind-down
   - Their internal dialogue when facing a difficult decision
   - How they've typically evolved from childhood to adulthood
   - What triggers their "flow state" vs what disrupts it

2. **strengths/blindspots/challenges**: For each existing item, ADD a second paragraph with:
   - A specific real-world scenario demonstrating this trait
   - The internal experience (what they're thinking/feeling)

3. **inRelationships/relationshipStyle**: ADD new paragraphs about:
   - How they handle conflict (specific dialogue examples)
   - What makes them feel loved vs. what pushes them away
   - Their attachment style tendencies

4. **careerPaths/careerMatches**: For each career, ADD:
   - A "typical Tuesday" narrative for this type in that role
   - Specific tasks that energize vs. drain them

5. **workStyle** (if exists): ADD paragraphs about:
   - Their ideal meeting format
   - How they handle interruptions
   - Their relationship with deadlines

CRITICAL RULES:
- Keep ALL existing content exactly as-is
- ADD new content to existing arrays/strings (append, don't replace)
- For string fields, concatenate new paragraphs with "\\n\\n"
- For arrays, append new items or expand existing items
- Return the COMPLETE JSON with both old and new content
- The final output MUST be ${targetWordCount}+ words

Return ONLY valid JSON, no markdown code blocks.`;
}

interface ExpansionTask {
  id: string;
  name: string;
  framework: "prism" | "mbti" | "enneagram";
  originalContent: any;
}

interface ExpansionResult {
  task: ExpansionTask;
  expandedContent: any;
  wordCount: number;
  success: boolean;
  error?: string;
}

async function expandSingleType(task: ExpansionTask): Promise<ExpansionResult> {
  const { id, name, framework, originalContent } = task;
  
  let currentContent = originalContent;
  let wordCount = countWords(originalContent);
  let attempts = 0;
  
  while (attempts <= MAX_RETRIES) {
    attempts++;
    
    try {
      let prompt: string;
      let systemPrompt = SYSTEM_PROMPT;
      
      if (attempts === 1) {
        // First attempt - use framework-specific prompt for full generation
        if (framework === "prism") {
          prompt = buildPRISMExpansionPrompt(id, currentContent);
        } else if (framework === "mbti") {
          prompt = buildMBTIExpansionPrompt(id.toUpperCase(), currentContent);
        } else {
          prompt = buildEnneagramExpansionPrompt(id, currentContent);
        }
      } else {
        // Retry - use EXTENSION approach (add to existing, don't regenerate)
        console.log(`  📝 ${name}: Extending existing ${wordCount} words...`);
        prompt = buildExtensionPrompt(currentContent, wordCount, TARGET_WORD_COUNT, framework);
        // Simpler system prompt for extension
        systemPrompt = `You are extending existing personality psychology content. Your job is to ADD new paragraphs and details to existing content to reach a word count target. Keep all existing content intact and append new material. Return valid JSON only.`;
      }
      
      const response = await generateContent([
        { role: "system", content: systemPrompt },
        { role: "user", content: prompt }
      ]);
      
      // Parse response - handle various formats
      let expandedContent = response.trim();
      
      // Remove markdown code blocks if present
      const jsonMatch = expandedContent.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        expandedContent = jsonMatch[1].trim();
      }
      
      // Try to find JSON object if there's extra text
      const jsonStart = expandedContent.indexOf('{');
      const jsonEnd = expandedContent.lastIndexOf('}');
      if (jsonStart !== -1 && jsonEnd !== -1 && jsonStart < jsonEnd) {
        expandedContent = expandedContent.slice(jsonStart, jsonEnd + 1);
      }
      
      const parsed = JSON.parse(expandedContent);
      
      // Preserve immutable fields for PRISM types
      if (framework === "prism") {
        const orig = originalContent as any;
        parsed.id = orig.id;
        parsed.pattern = orig.pattern;
        parsed.color = orig.color;
        parsed.rarity = orig.rarity;
        parsed.icon = orig.icon;
        parsed.famousExamples = orig.famousExamples;
      }
      
      const newWordCount = countWords(parsed);
      
      // Only accept if we made progress
      if (newWordCount > wordCount) {
        wordCount = newWordCount;
        currentContent = parsed;
      }
      
      if (wordCount >= TARGET_WORD_COUNT) {
        console.log(`  ✅ ${name} expanded (~${wordCount} words) [attempt ${attempts}]`);
        return { task, expandedContent: currentContent, wordCount, success: true };
      } else if (attempts <= MAX_RETRIES) {
        console.log(`  🔄 ${name} at ~${wordCount} words, extending to ${TARGET_WORD_COUNT}+...`);
      }
      
    } catch (error: any) {
      if (attempts > MAX_RETRIES) {
        console.log(`  ❌ ${name} failed after ${attempts} attempts: ${error.message?.slice(0, 100)}`);
        return { task, expandedContent: currentContent, wordCount, success: wordCount > countWords(originalContent), error: error.message };
      }
      console.log(`  ⚠️ ${name} attempt ${attempts} failed, retrying...`);
      await sleep(2000); // Brief pause before retry on error
    }
  }
  
  // Return best effort if we couldn't reach target
  console.log(`  ⚠️ ${name} completed at ~${wordCount} words (target: ${TARGET_WORD_COUNT})`);
  return { task, expandedContent: currentContent, wordCount, success: true };
}

async function runInBatches<T, R>(
  items: T[],
  batchSize: number,
  delayMs: number,
  processor: (item: T) => Promise<R>
): Promise<R[]> {
  const results: R[] = [];
  
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize);
    const batchNum = Math.floor(i / batchSize) + 1;
    const totalBatches = Math.ceil(items.length / batchSize);
    
    console.log(`\n📦 Processing batch ${batchNum}/${totalBatches} (${batch.length} items)...\n`);
    
    const batchResults = await Promise.all(batch.map(processor));
    results.push(...batchResults);
    
    if (i + batchSize < items.length) {
      console.log(`\n⏳ Waiting ${delayMs/1000}s before next batch...`);
      await sleep(delayMs);
    }
  }
  
  return results;
}

async function main() {
  console.log("🚀 PRISM-7 Content Expansion Script (PARALLEL MODE)");
  console.log("====================================================");
  console.log(`Model: ${MODEL}`);
  console.log(`Target: ${TARGET_WORD_COUNT}+ words per type`);
  console.log(`Batch size: ${PARALLEL_BATCH_SIZE} concurrent requests`);
  console.log(`Max retries per type: ${MAX_RETRIES}`);
  console.log(`Types to expand: 37 (12 PRISM + 16 MBTI + 9 Enneagram)`);
  console.log();

  if (!process.env.OPENROUTER_API_KEY) {
    console.error("❌ OPENROUTER_API_KEY not found in environment");
    process.exit(1);
  }

  const startTime = Date.now();

  // Build task list
  const tasks: ExpansionTask[] = [];
  
  // PRISM archetypes
  for (const archetype of archetypes) {
    tasks.push({
      id: archetype.id,
      name: archetype.name,
      framework: "prism",
      originalContent: archetype
    });
  }
  
  // MBTI types
  for (const typeKey of Object.keys(mbtiTypes)) {
    tasks.push({
      id: typeKey,
      name: typeKey.toUpperCase(),
      framework: "mbti",
      originalContent: mbtiTypes[typeKey]
    });
  }
  
  // Enneagram types
  for (const typeNum of Object.keys(enneagramTypes)) {
    tasks.push({
      id: typeNum,
      name: `Type ${typeNum} - ${enneagramTypes[typeNum].name}`,
      framework: "enneagram",
      originalContent: enneagramTypes[typeNum]
    });
  }

  console.log(`📋 Total tasks: ${tasks.length}`);

  // Run all expansions in parallel batches
  const results = await runInBatches(
    tasks,
    PARALLEL_BATCH_SIZE,
    DELAY_BETWEEN_BATCHES,
    expandSingleType
  );

  // Organize results by framework
  const prismResults: any[] = [];
  const mbtiResults: Record<string, any> = {};
  const enneagramResults: Record<string, any> = {};

  for (const result of results) {
    if (result.task.framework === "prism") {
      prismResults.push(result.expandedContent);
    } else if (result.task.framework === "mbti") {
      mbtiResults[result.task.id] = result.expandedContent;
    } else {
      enneagramResults[result.task.id] = result.expandedContent;
    }
  }

  // Save all results
  const prismPath = path.join(__dirname, "..", "lib", "archetypes-expanded.json");
  fs.writeFileSync(prismPath, JSON.stringify(prismResults, null, 2));
  console.log(`\n📁 Saved PRISM archetypes to ${prismPath}`);

  const mbtiPath = path.join(__dirname, "..", "lib", "mbti-content-expanded.json");
  fs.writeFileSync(mbtiPath, JSON.stringify(mbtiResults, null, 2));
  console.log(`📁 Saved MBTI types to ${mbtiPath}`);

  const enneagramPath = path.join(__dirname, "..", "lib", "enneagram-content-expanded.json");
  fs.writeFileSync(enneagramPath, JSON.stringify(enneagramResults, null, 2));
  console.log(`📁 Saved Enneagram types to ${enneagramPath}`);

  // Summary
  const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
  const successful = results.filter(r => r.success).length;
  const atTarget = results.filter(r => r.wordCount >= TARGET_WORD_COUNT).length;
  const totalWords = results.reduce((sum, r) => sum + r.wordCount, 0);
  const avgWords = Math.round(totalWords / results.length);

  console.log("\n====================================================");
  console.log(`✅ Content expansion complete!`);
  console.log(`⏱️  Total time: ${elapsed} minutes`);
  console.log(`📊 Success rate: ${successful}/${results.length}`);
  console.log(`🎯 At target (${TARGET_WORD_COUNT}+): ${atTarget}/${results.length}`);
  console.log(`📝 Average word count: ${avgWords}`);
  console.log(`📝 Total words generated: ${totalWords.toLocaleString()}`);
  console.log();
  
  // Show any that didn't hit target
  const belowTarget = results.filter(r => r.wordCount < TARGET_WORD_COUNT);
  if (belowTarget.length > 0) {
    console.log("⚠️ Types below target word count:");
    for (const r of belowTarget) {
      console.log(`   - ${r.task.name}: ${r.wordCount} words`);
    }
  }
  
  console.log();
  console.log("Next steps:");
  console.log("1. Review the expanded JSON files in frontend/lib/");
  console.log("2. Run: npx tsx scripts/integrate-expanded-content.ts");
  console.log("3. Test the pages to verify content displays correctly");
}

main();

