/**
 * Content Expansion Script for Main Type Pages
 * Expands 37 personality type pages to ~7,500 words each
 * Uses OpenRouter with Gemini 3 Pro Preview
 * 
 * Usage: npx tsx scripts/expand-type-content.ts
 */

import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

// Import the actual content
import { archetypes } from "../lib/archetypes";
import { mbtiTypes } from "../lib/mbti-content";
import { enneagramTypes } from "../lib/enneagram-content";

dotenv.config({ path: ".env.local" });

const OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1";
const MODEL = "google/gemini-3-pro-preview";

// Rate limiting
const DELAY_BETWEEN_REQUESTS = 5000; // 5 seconds between requests to avoid rate limits

interface OpenRouterMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

function getApiKey(): string {
  const key = process.env.OPENROUTER_API_KEY;
  if (!key) {
    throw new Error("OPENROUTER_API_KEY is not set in environment variables");
  }
  return key;
}

async function generateContent(messages: OpenRouterMessage[]): Promise<string> {
  const apiKey = getApiKey();

  const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
      "HTTP-Referer": "https://prism7.app",
      "X-Title": "PRISM-7 Content Expander",
    },
    body: JSON.stringify({
      model: MODEL,
      messages,
      temperature: 0.75,
      max_tokens: 16000,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`OpenRouter API error: ${response.status} - ${error}`);
  }

  const data = await response.json();
  return data.choices[0]?.message?.content || "";
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ============================================================================
// PRISM-7 METHODOLOGY CONTEXT
// ============================================================================

const PRISM_METHODOLOGY_CONTEXT = `
PRISM-7 is a next-generation personality assessment built on the HEXACO+ model, which improves upon traditional frameworks like MBTI and Big Five in several key ways:

1. **HEXACO Foundation**: Unlike MBTI's binary categories or Big Five's limited scope, HEXACO adds the crucial Honesty-Humility dimension, which predicts ethical behavior, manipulation tendencies, and authentic vs. performative social engagement.

2. **Seven Dimensions**: PRISM-7 measures:
   - Openness (creativity, intellectual curiosity, aesthetic sensitivity)
   - Conscientiousness (organization, self-discipline, goal-pursuit)
   - Extraversion (social energy, assertiveness, positive emotionality)
   - Agreeableness (cooperation, trust, empathy)
   - Emotional Resilience (stress tolerance, emotional stability - importantly framed positively, not as "neuroticism")
   - Honesty-Humility (authenticity, fairness, lack of entitlement)
   - Adaptability (flexibility, comfort with change, cognitive agility)

3. **Why This Matters**: 
   - MBTI uses binary categories (you're either Introverted OR Extraverted), ignoring that most people fall in the middle
   - MBTI's "Intuition vs. Sensing" conflates multiple distinct traits
   - Big Five's "Neuroticism" is deficit-focused; PRISM-7's "Emotional Resilience" is strength-focused
   - Neither MBTI nor Big Five capture Honesty-Humility, which is crucial for predicting workplace ethics, relationship authenticity, and leadership integrity
   - Neither adequately measures Adaptability, increasingly vital in modern environments

4. **Research Backing**: HEXACO has stronger predictive validity than Big Five for antisocial behavior, job performance in trust-sensitive roles, and relationship satisfaction. PRISM-7 adds Adaptability based on contemporary research on psychological flexibility.

When writing about personality types, integrate these insights to show how PRISM-7 provides a more complete, nuanced picture than legacy frameworks.
`;

// ============================================================================
// EXPANSION PROMPTS
// ============================================================================

const SYSTEM_PROMPT = `You are an expert personality psychology writer creating deeply detailed, original content for a next-generation personality assessment platform (PRISM-7).

${PRISM_METHODOLOGY_CONTEXT}

CRITICAL WRITING REQUIREMENTS:

1. **ABSOLUTE ORIGINALITY**: Your content must feel hand-crafted by a seasoned psychologist, not generated by AI. Avoid:
   - Clichéd openings like "In today's fast-paced world..." or "When it comes to..."
   - Filler phrases like "It's important to note that..." or "One might say..."
   - Generic platitudes that could apply to any type
   - Predictable paragraph structures

2. **DEEP PSYCHOLOGICAL INSIGHT**: Go beyond surface behaviors to underlying mechanisms:
   - What cognitive patterns drive this type's behavior?
   - What are the second and third-order effects of their core traits?
   - How do their strengths become weaknesses in specific contexts?
   - What developmental trajectory is typical for this type?

3. **VIVID SPECIFICITY**: Replace abstract descriptions with concrete scenarios:
   - Instead of "They are good at planning" → "They're the person who creates a shared Google Doc for a weekend trip, complete with backup restaurant options and rain contingencies"
   - Include sensory details, dialogue snippets, and recognizable micro-moments

4. **PRISM-7 INTEGRATION**: Show how this type maps to PRISM-7 dimensions and what traditional frameworks miss about them. Highlight the nuances that HEXACO+ captures that MBTI/Enneagram cannot.

5. **INTELLECTUAL HONESTY**: Acknowledge complexity, paradoxes, and individual variation. Avoid making types sound like monolithic categories.

6. **TARGET: 7,500+ WORDS**: This is a comprehensive resource. Each section should be rich with detail, examples, and insight. Do not pad with repetition—add genuine new content.

OUTPUT FORMAT: Return valid JSON matching the exact structure provided, with dramatically expanded content in each field.`;

function buildMBTIExpansionPrompt(typeCode: string, existingContent: any): string {
  return `Expand this MBTI type content to approximately 7,500 words total while maintaining the exact JSON structure.

CURRENT CONTENT FOR ${typeCode}:
${JSON.stringify(existingContent, null, 2)}

EXPANSION REQUIREMENTS:

1. **description[]**: Expand from ${existingContent.description?.length || 0} paragraphs to 10-14 substantial paragraphs. Cover:
   - The lived experience of being this type (what does their internal world feel like?)
   - How they developed these patterns (childhood, formative experiences)
   - The paradoxes and tensions within this type
   - How they're commonly misunderstood
   - Their relationship with their inferior function
   - How they change across life stages
   - What they're like when healthy vs. stressed
   - Their unique gifts that other types cannot replicate
   
2. **cognitiveFunctions**: Expand each function description to 150-200 words with:
   - How this function manifests in daily decisions
   - Specific examples of this function in action
   - How it interacts with other functions in the stack
   - Common misunderstandings about this function in this position

3. **strengths[]**: Expand each strength object to include 80-120 word descriptions with:
   - Specific workplace/relationship scenarios demonstrating this strength
   - The underlying cognitive mechanism
   - How this strength can be developed further
   - When this strength might be mistaken for something else

4. **blindspots[]**: Expand each to 80-120 words with:
   - Real consequences of this blindspot (not just abstract descriptions)
   - How it shows up in relationships vs. work vs. personal life
   - Compassionate framing—why this blindspot exists
   - Practical mitigation strategies

5. **inRelationships**: Expand each section (romantic, friendship, workplace) to 200-300 words with:
   - Specific interaction patterns and dialogue examples
   - What partners/friends/colleagues often misunderstand
   - How they show love/loyalty in ways others might miss
   - Compatibility nuances beyond simple type pairings

6. **careerPaths[]**: Expand each career to include 100-150 word reasons with:
   - Day-in-the-life scenarios
   - Specific tasks that energize vs. drain this type
   - Career progression typical for this type
   - Warning signs of poor fit

7. **growthAdvice[]**: Expand each piece of advice to 80-120 words with:
   - Why this specific advice matters for this type
   - Concrete first steps to implement
   - What internal resistance they'll face
   - Signs of progress

8. **prismCorrelation**: Expand keyDimensions to 150-200 words explaining:
   - Exactly how this type maps to PRISM-7 dimensions
   - What PRISM-7 reveals that MBTI misses about this type
   - Why HEXACO+ provides a more nuanced understanding

Return ONLY valid JSON matching the original structure with no markdown formatting or code blocks.`;
}

function buildEnneagramExpansionPrompt(typeNum: string, existingContent: any): string {
  return `Expand this Enneagram type content to approximately 7,500 words total while maintaining the exact JSON structure.

CURRENT CONTENT FOR TYPE ${typeNum}:
${JSON.stringify(existingContent, null, 2)}

EXPANSION REQUIREMENTS:

1. **description[]**: Expand from ${existingContent.description?.length || 0} paragraphs to 10-14 substantial paragraphs. Cover:
   - The core wound that created this fixation
   - The internal logic of their coping strategy
   - How the core fear manifests in subtle, everyday moments
   - The paradox between what they seek and how they pursue it
   - Their relationship with their body/heart/head center
   - How childhood experiences shaped this pattern
   - The spiritual or existential dimension of their journey
   - What liberation looks like for this type

2. **healthLevels**: Expand each level (healthy, average, unhealthy) to 200-250 words with:
   - Observable behaviors at this level
   - Internal experience at this level
   - How others experience them at this level
   - Triggers that move them between levels
   - What this level looks like in relationships vs. work

3. **wings**: Expand each wing description to 150-200 words with:
   - How the wing modifies the core type's expression
   - Specific behavioral differences between the two wings
   - Career implications of each wing
   - Relationship patterns unique to each wing

4. **growthLine & stressLine**: Expand each to 150-200 words with:
   - How movement to this point manifests behaviorally
   - What triggers movement in this direction
   - How to recognize you're moving toward growth vs. stress
   - Integration of healthy aspects from connected types

5. **strengths[]**: Expand each to 60-80 words with specific examples
6. **challenges[]**: Expand each to 60-80 words with compassionate framing

7. **inRelationships**: Expand to 300-400 words covering:
   - Core relationship patterns rooted in the type's fixation
   - How the core fear shows up in intimacy
   - What they need from partners that they struggle to ask for
   - Their unique gifts as partners
   - Common relationship pitfalls and how to avoid them

8. **careerPaths[]**: Expand each career to include 100-120 word reasons with day-in-the-life scenarios

9. **growthAdvice[]**: Expand each to 80-100 words with:
   - The psychological mechanism behind the advice
   - Practical first steps
   - Signs of progress

10. **prismCorrelation**: Expand keyDimensions to 150-200 words explaining how PRISM-7 dimensions capture what Enneagram describes motivationally, and what HEXACO+ adds to understanding this type.

Return ONLY valid JSON matching the original structure with no markdown formatting or code blocks.`;
}

function buildPRISMExpansionPrompt(typeId: string, existingContent: any): string {
  return `Expand this PRISM-7 archetype content to approximately 7,500 words total while maintaining the exact JSON structure.

CURRENT CONTENT FOR ${typeId.toUpperCase()}:
${JSON.stringify(existingContent, null, 2)}

EXPANSION REQUIREMENTS:

1. **description[]**: Expand from ${existingContent.description?.length || 0} paragraphs to 10-14 substantial paragraphs. Cover:
   - What makes this archetype distinct from superficially similar types
   - The lived experience—what does it feel like to be this archetype?
   - How this pattern of PRISM-7 dimensions creates emergent properties
   - The developmental origins of this archetype
   - Common misconceptions about this archetype
   - How they experience flow states and what blocks them
   - Their unique contribution that no other archetype can provide
   - The growth edge—where their evolution lies

2. **strengths[]**: Expand each strength to 60-80 words with:
   - Specific manifestations in different contexts
   - The PRISM-7 dimensions underlying this strength
   - How to leverage this strength more intentionally

3. **growthAreas[]**: Expand each to 60-80 words with:
   - Why this is challenging given their PRISM-7 profile
   - Compassionate framing of the underlying need
   - Practical development strategies

4. **careerMatches[]**: Expand each career explanation to 100-150 words with:
   - Day-in-the-life scenarios
   - Why the PRISM-7 dimension pattern makes this a fit
   - What aspects of this career they'd need to watch out for
   - Career progression trajectory

5. **workStyle**: Expand to 200-300 words covering:
   - Ideal physical environment details
   - Meeting and collaboration preferences
   - Communication style at work
   - How they handle deadlines and pressure
   - What drains them vs. energizes them at work

6. **relationshipStyle**: Expand to 200-300 words covering:
   - How their PRISM-7 dimensions show up in intimacy
   - What they offer partners that's unique
   - What they need that they may not articulate
   - Common misunderstandings partners have
   - Long-term relationship evolution patterns

7. **communicationStyle**: Expand to 150-200 words with specific examples of:
   - Their verbal patterns and preferences
   - Non-verbal communication tendencies
   - How they handle conflict communication
   - Written vs. verbal preferences

8. **atYourBest**: Expand to 150-200 words with:
   - Specific scenarios of peak performance
   - What conditions enable this state
   - How others experience them at their best

9. **whenStressed**: Expand to 150-200 words with:
   - Observable stress behaviors
   - Internal experience of stress
   - What triggers stress for this archetype
   - De-escalation strategies

Return ONLY valid JSON matching the original structure with no markdown formatting or code blocks.`;
}

// ============================================================================
// MAIN EXECUTION
// ============================================================================

async function expandMBTITypes() {
  console.log("\n📚 Expanding MBTI Types...\n");
  
  const typeKeys = Object.keys(mbtiTypes);
  const expandedTypes: Record<string, any> = {};
  
  for (const typeKey of typeKeys) {
    const existingContent = mbtiTypes[typeKey];
    console.log(`  🔄 Expanding ${typeKey.toUpperCase()}...`);
    
    try {
      const prompt = buildMBTIExpansionPrompt(typeKey.toUpperCase(), existingContent);
      
      const response = await generateContent([
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: prompt }
      ]);
      
      // Parse the response
      let expandedContent = response;
      const jsonMatch = response.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        expandedContent = jsonMatch[1].trim();
      }
      
      try {
        expandedTypes[typeKey] = JSON.parse(expandedContent);
        const wordCount = JSON.stringify(expandedTypes[typeKey]).split(/\s+/).length;
        console.log(`  ✅ ${typeKey.toUpperCase()} expanded (~${wordCount} words)`);
      } catch (parseError) {
        console.log(`  ❌ Failed to parse JSON for ${typeKey}, saving raw response...`);
        // Save raw response for debugging
        const rawPath = path.join(__dirname, `mbti-${typeKey}-raw.txt`);
        fs.writeFileSync(rawPath, response);
        console.log(`     Saved to ${rawPath}`);
      }
      
      await sleep(DELAY_BETWEEN_REQUESTS);
      
    } catch (error) {
      console.error(`  ❌ Error expanding ${typeKey}:`, error);
    }
  }
  
  // Save expanded content
  const outputPath = path.join(__dirname, "..", "lib", "mbti-content-expanded.json");
  fs.writeFileSync(outputPath, JSON.stringify(expandedTypes, null, 2));
  console.log(`\n📁 Saved expanded MBTI content to ${outputPath}`);
  
  return expandedTypes;
}

async function expandEnneagramTypes() {
  console.log("\n📚 Expanding Enneagram Types...\n");
  
  const typeNums = Object.keys(enneagramTypes);
  const expandedTypes: Record<string, any> = {};
  
  for (const typeNum of typeNums) {
    const existingContent = enneagramTypes[typeNum];
    console.log(`  🔄 Expanding Type ${typeNum} - ${existingContent.name}...`);
    
    try {
      const prompt = buildEnneagramExpansionPrompt(typeNum, existingContent);
      
      const response = await generateContent([
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: prompt }
      ]);
      
      let expandedContent = response;
      const jsonMatch = response.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        expandedContent = jsonMatch[1].trim();
      }
      
      try {
        expandedTypes[typeNum] = JSON.parse(expandedContent);
        const wordCount = JSON.stringify(expandedTypes[typeNum]).split(/\s+/).length;
        console.log(`  ✅ Type ${typeNum} expanded (~${wordCount} words)`);
      } catch (parseError) {
        console.log(`  ❌ Failed to parse JSON for Type ${typeNum}, saving raw response...`);
        const rawPath = path.join(__dirname, `enneagram-${typeNum}-raw.txt`);
        fs.writeFileSync(rawPath, response);
        console.log(`     Saved to ${rawPath}`);
      }
      
      await sleep(DELAY_BETWEEN_REQUESTS);
      
    } catch (error) {
      console.error(`  ❌ Error expanding Type ${typeNum}:`, error);
    }
  }
  
  const outputPath = path.join(__dirname, "..", "lib", "enneagram-content-expanded.json");
  fs.writeFileSync(outputPath, JSON.stringify(expandedTypes, null, 2));
  console.log(`\n📁 Saved expanded Enneagram content to ${outputPath}`);
  
  return expandedTypes;
}

async function expandPRISMArchetypes() {
  console.log("\n📚 Expanding PRISM-7 Archetypes...\n");
  
  const expandedArchetypes: any[] = [];
  
  for (const archetype of archetypes) {
    console.log(`  🔄 Expanding ${archetype.name}...`);
    
    try {
      const prompt = buildPRISMExpansionPrompt(archetype.id, archetype);
      
      const response = await generateContent([
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: prompt }
      ]);
      
      let expandedContent = response;
      const jsonMatch = response.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        expandedContent = jsonMatch[1].trim();
      }
      
      try {
        const parsed = JSON.parse(expandedContent);
        // Preserve fields that shouldn't change
        parsed.id = archetype.id;
        parsed.pattern = archetype.pattern;
        parsed.color = archetype.color;
        parsed.rarity = archetype.rarity;
        parsed.icon = archetype.icon;
        parsed.famousExamples = archetype.famousExamples; // Keep original examples with images
        
        expandedArchetypes.push(parsed);
        const wordCount = JSON.stringify(parsed).split(/\s+/).length;
        console.log(`  ✅ ${archetype.name} expanded (~${wordCount} words)`);
      } catch (parseError) {
        console.log(`  ❌ Failed to parse JSON for ${archetype.id}, saving raw response...`);
        const rawPath = path.join(__dirname, `prism-${archetype.id}-raw.txt`);
        fs.writeFileSync(rawPath, response);
        console.log(`     Saved to ${rawPath}`);
        // Add original archetype as fallback
        expandedArchetypes.push(archetype);
      }
      
      await sleep(DELAY_BETWEEN_REQUESTS);
      
    } catch (error) {
      console.error(`  ❌ Error expanding ${archetype.id}:`, error);
      // Add original archetype as fallback
      expandedArchetypes.push(archetype);
    }
  }
  
  const outputPath = path.join(__dirname, "..", "lib", "archetypes-expanded.json");
  fs.writeFileSync(outputPath, JSON.stringify(expandedArchetypes, null, 2));
  console.log(`\n📁 Saved expanded PRISM archetypes to ${outputPath}`);
  
  return expandedArchetypes;
}

async function main() {
  console.log("🚀 PRISM-7 Content Expansion Script");
  console.log("===================================");
  console.log(`Model: ${MODEL}`);
  console.log(`Target: ~7,500 words per type`);
  console.log(`Types to expand: 37 (12 PRISM + 16 MBTI + 9 Enneagram)`);
  console.log();

  if (!process.env.OPENROUTER_API_KEY) {
    console.error("❌ OPENROUTER_API_KEY not found in environment");
    process.exit(1);
  }

  const startTime = Date.now();

  try {
    // Expand each framework
    await expandPRISMArchetypes();
    await expandMBTITypes();
    await expandEnneagramTypes();

    const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
    console.log("\n===================================");
    console.log(`✅ Content expansion complete!`);
    console.log(`⏱️  Total time: ${elapsed} minutes`);
    console.log();
    console.log("Next steps:");
    console.log("1. Review the expanded JSON files in frontend/lib/");
    console.log("2. Integrate expanded content into TypeScript source files");
    console.log("3. Test the pages to verify content displays correctly");
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}

main();

